name: lsmaker
channels:
- conda-forge
- defaults
- atleaf
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy
- scipy
- pandas
- gdal
- fiona
- rasterio>=1.0
- shapely
- pyproj>=2.0
- gis-utils>=0.2.5
