name: lsmaker
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- requests
- numpy
- scipy
- pandas
- gdal
- fiona
- rasterio>=1.0
- shapely
- pyproj>=2.0
- pip
- pip:
  - gis-utils>=0.2.5
