name: lsmaker_ci
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy
- scipy
- pandas
- gdal
- fiona
- rasterio
- shapely
- pyproj
- descartes
- geopandas
- codecov
- coverage
- flake8
- pytest
- sphinx<7
- numpydoc
- nbsphinx  # for rendering notebooks in sphinx-generated docs
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
  - gis-utils
